_target_: src.models.mlp_module.MLPModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

network:
  _target_: src.models.mlp.MLP
  input_size: 2381
  hidden_units: [1024, 512, 256]
