# @package _global_

defaults:
  - _self_
  - data: ember.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: mlp.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  - experiment: null

task_name: "default"
train_eval: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
